package View;

import Controller.UserController;

public class UserGUI extends javax.swing.JFrame {
    
    private static UserController userController;
    private String username;

    public UserGUI(String username) {
        initComponents();
        this.username = username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        movieList = new javax.swing.JTable();
        nextButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        adultQuantity = new javax.swing.JComboBox<>();
        childQuantity = new javax.swing.JComboBox<>();
        seniorQuantity = new javax.swing.JComboBox<>();
        studentQuantity = new javax.swing.JComboBox<>();
        militaryQuantity = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        totalPriceLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        taxLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        adultPrice = new javax.swing.JLabel();
        childPrice = new javax.swing.JLabel();
        seniorPrice = new javax.swing.JLabel();
        studentPrice = new javax.swing.JLabel();
        militaryPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        movieList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie", "Rating", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(movieList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 437, 237));

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 575, 92, -1));

        jLabel1.setText("Adult (ages 13 & up)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 291, -1, -1));

        jLabel2.setText("Child (ages 2-12)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 334, -1, -1));

        jLabel3.setText("Senior (ages 65 & up) ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 375, -1, -1));

        jLabel4.setText("Student Discount (with ID)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 416, -1, -1));

        jLabel5.setText("Military Discount (with ID)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 457, -1, -1));

        jLabel6.setText("Quantity");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 52, -1));

        adultQuantity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        adultQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adultQuantityActionPerformed(evt);
            }
        });
        getContentPane().add(adultQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        childQuantity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        childQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childQuantityActionPerformed(evt);
            }
        });
        getContentPane().add(childQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 331, -1, -1));

        seniorQuantity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        seniorQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seniorQuantityActionPerformed(evt);
            }
        });
        getContentPane().add(seniorQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 372, -1, -1));

        studentQuantity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        studentQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentQuantityActionPerformed(evt);
            }
        });
        getContentPane().add(studentQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 413, -1, -1));

        militaryQuantity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        militaryQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                militaryQuantityActionPerformed(evt);
            }
        });
        getContentPane().add(militaryQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 454, -1, -1));

        jLabel7.setText("Ticket Price");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 62, -1));

        jLabel8.setText("$10.69");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        jLabel9.setText("$7.39");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        jLabel10.setText("$8.89");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, -1));

        jLabel11.setText("$8.89");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, -1));

        jLabel12.setText("$8.89");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, -1));

        jLabel13.setText("Total Price");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 515, 145, 10));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("You Pay:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, -1, -1));

        totalPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(totalPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 530, 90, 29));

        jLabel16.setText("Tax:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 495, -1, -1));
        getContentPane().add(taxLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 495, 70, 14));

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 575, 92, -1));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 610));
        getContentPane().add(adultPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 60, 10));
        getContentPane().add(childPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 60, 10));
        getContentPane().add(seniorPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 60, 10));
        getContentPane().add(studentPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 60, 10));
        getContentPane().add(militaryPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 60, 10));

        setSize(new java.awt.Dimension(473, 648));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adultQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adultQuantityActionPerformed
        userController.calculateAdultPrice();
    }//GEN-LAST:event_adultQuantityActionPerformed

    private void childQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childQuantityActionPerformed
        userController.calculateChildPrice();
    }//GEN-LAST:event_childQuantityActionPerformed

    private void seniorQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seniorQuantityActionPerformed
        userController.calculateSeniorPrice();
    }//GEN-LAST:event_seniorQuantityActionPerformed

    private void studentQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentQuantityActionPerformed
        userController.calculateStudentPrice();
    }//GEN-LAST:event_studentQuantityActionPerformed

    private void militaryQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_militaryQuantityActionPerformed
        userController.calculateMilitaryPrice();
    }//GEN-LAST:event_militaryQuantityActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        userController.next();
    }//GEN-LAST:event_nextButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        userController.logout();
    }//GEN-LAST:event_logoutButtonActionPerformed

    public void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        UserGUI userGUI = new UserGUI(username);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                userGUI.setVisible(true);
            }
        });
        
        userController = new UserController(userGUI);
    }
    
    public javax.swing.JComboBox<String> getAdultQuantity() {
        return adultQuantity;
    }
    
    public javax.swing.JComboBox<String> getChildQuantity() {
        return childQuantity;
    }
    
    public javax.swing.JComboBox<String> getMilitaryQuantity() {
        return militaryQuantity;
    }
    
    public javax.swing.JComboBox<String> getSeniorQuantity() {
        return seniorQuantity;
    }
    
    public javax.swing.JComboBox<String> getStudentQuantity() {
        return studentQuantity;
    }
    
    public javax.swing.JLabel getTaxLabel() {
        return taxLabel;
    }
    
    public javax.swing.JLabel getTotalPriceLabel() {
        return totalPriceLabel;
    }
    
    public javax.swing.JTable getMovieList() {
        return movieList;
    }
    
    public javax.swing.JLabel getAdultLabel() {
        return adultPrice;
    }
    
    public javax.swing.JLabel getChildLabel() {
        return childPrice;
    }
    
    public javax.swing.JLabel getSeniorLabel() {
        return seniorPrice;
    }
    
    public javax.swing.JLabel getStudentLabel() {
        return studentPrice;
    }
    
    public javax.swing.JLabel getMilitaryLabel() {
        return militaryPrice;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adultPrice;
    private javax.swing.JComboBox<String> adultQuantity;
    private javax.swing.JLabel childPrice;
    private javax.swing.JComboBox<String> childQuantity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel militaryPrice;
    private javax.swing.JComboBox<String> militaryQuantity;
    private javax.swing.JTable movieList;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel seniorPrice;
    private javax.swing.JComboBox<String> seniorQuantity;
    private javax.swing.JLabel studentPrice;
    private javax.swing.JComboBox<String> studentQuantity;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JLabel totalPriceLabel;
    // End of variables declaration//GEN-END:variables
}
